language: python
repo_token: M39m4X03sxZqHYmwkOHtgWZhWAFUuoX9Y
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
before_script:
  - pip install coveralls
  - coverage run --source= test_Slist.py
script:
  - pytest
after_success:
  - coverage run --source=my_package setup.py test
